[package]
name = "centrium-grpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1.0", features = ["full"] }
protobuf = "3.2.0"
prost = "0.12.6"
tonic = { version = "0.11.0" }

[build-dependencies]
tonic-build = { version = "0.9.2", features = ["prost"] }